// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jdbcipneiioimvtflfgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYmNpcG5laWlvaW12dGZsZmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDQwODAsImV4cCI6MjA2ODY4MDA4MH0.L7YTuH0n2ur9-i-qApjR_k2uHAgksQB0jelVlTmY7JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);